version: '3'

services:
  angular-app:
    build: ./dashboard-oorzaak
    ports:
      - "4200:4200"
    networks:
      - my_network

  streamlit-app:
    build: ./streamlit
    ports:
      - "8501:8501"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
